# Generated by Django 4.2.1 on 2023-05-23 13:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrequest',
            old_name='password',
            new_name='vr_password',
        ),
        migrations.RenameField(
            model_name='userrequest',
            old_name='username',
            new_name='vr_username',
        ),
        migrations.RemoveField(
            model_name='userrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='userrequest',
            name='shift_date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userrequest',
            name='request_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='user.userlogin'),
        ),
    ]
